### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Adamkadaban** [ayserjamshidi/Chegg-Device-Bypass#3]
Don't think this works anymore. It looks like Chegg now gives a static blurred image for the answer if you're not a registered device.

**Comment by AyserJamshidi** [comment]
Hi there.  I've just tested using Microsoft Edge latest stable build (v97.0.1072.55 x64) and answers still show just fine for me -- you can view [my results (left browser was loaded with the extension enabled)](https://i.imgur.com/eM1aoKz.png).  What browser and version are you using?  Have you tried disabling every other extension apart from this one to see if there's some sort of conflict going on?

**Comment by Adamkadaban** [comment]
I'm on `Version 97.0.4692.71 (Official Build) (64-bit)` I also tried disabling all other extensions. I'll try on edge in a bit
